// import { NetworkConfig } from "@stafihub/types";

export const cosmosConfig: any = {
  cosmosHub: {
    chainId: "stafihub-testnet-1",
    chainName: "stafihub-testnet-1",
    rpc: "https://test-rpc1.stafihub.io",
    restEndpoint: "https://test-rest-rpc1.stafihub.io",
    denom: "ufis",
    coinDenom: "ufis",
    decimals: 6,
    bech32Config: {
      bech32PrefixAccAddr: "stafi",
      bech32PrefixAccPub: "stafipub",
      bech32PrefixValAddr: "stafivaloper",
      bech32PrefixValPub: "stafivaloperpub",
      bech32PrefixConsAddr: "stafivalcons",
      bech32PrefixConsPub: "stafivalconspub",
    },
  },
  stafiHub: {
    chainId: "stafihub-testnet-1",
    chainName: "stafihub-testnet-1",
    rpc: "https://test-rpc1.stafihub.io",
    restEndpoint: "https://test-rest-rpc1.stafihub.io",
    denom: "ufis",
    coinDenom: "ufis",
    decimals: 6,
    bech32Config: {
      bech32PrefixAccAddr: "stafi",
      bech32PrefixAccPub: "stafipub",
      bech32PrefixValAddr: "stafivaloper",
      bech32PrefixValPub: "stafivaloperpub",
      bech32PrefixConsAddr: "stafivalcons",
      bech32PrefixConsPub: "stafivalconspub",
    },
  },
  terra: {
    chainId: "terra-stafi-1",
    chainName: "terra-stafi-1",
    rpc: "https://test-terra-rpc1.stafi.io",
    restEndpoint: "https://test-terra-rest1.stafi.io",
    denom: "uluna",
    coinDenom: "uluna",
    decimals: 6,
    bech32Config: {
      bech32PrefixAccAddr: "terra",
      bech32PrefixAccPub: "terrapub",
      bech32PrefixValAddr: "terravaloper",
      bech32PrefixValPub: "terravaloperpub",
      bech32PrefixConsAddr: "terravalcons",
      bech32PrefixConsPub: "terravalconspub",
    },
  },
  iris: {
    chainId: "iris-stafi-1",
    chainName: "iris-stafi-1",
    rpc: "https://test-iris-rpc1.stafihub.io",
    restEndpoint: "https://test-iris-rest1.stafihub.io",
    denom: "uiris",
    coinDenom: "uiris",
    decimals: 6,
    bech32Config: {
      bech32PrefixAccAddr: "iaa",
      bech32PrefixAccPub: "iap",
      bech32PrefixValAddr: "iva",
      bech32PrefixValPub: "ivp",
      bech32PrefixConsAddr: "ica",
      bech32PrefixConsPub: "icp",
    },
  },
};
